### ISSUE TITLE
example payer id is not a quarry param

### ISSUE THREAD

**Issue by AmrEl-basuony** [MRSEREY/flutter_paypal_sdk#1]
in your example the way you showed how to get payer id is wrong change it to 
`payerId = url.value.substring(url.value.indexOf("PayerID%3D") + "PayerID%3D".length).removeAllWhitespace;`

**Comment by MRSEREY** [comment]
Hi @AmrEl-basuony , I don't think so, since it is already parsed from the Uri.
for example:
final uri = Uri.parse('https://example.com/api/fetch?PayerID =10,&Price=100');
print(uri.queryParameters) // output: {PayerID: 10, Price: 100}

to access PayerID should be: 
final payerId = uri.queryParameters['PayerID'];
